default: &default
  adapter: postgresql
  encoding: unicode
  database: labotica
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: lphant
  password: lphant
  host: localhost

development:
  <<: *default
